Operações matriciais
====================


Uma das principais vantagens da estrutura *ndarray* é sua habilidade de processamento matricial.
Assim, para se multiplicar todos os elementos de um array por um escalar basta escrever *a * 5*, por
exemplo. Para se fazer qualquer operação lógica ou aritmética entre arrays, basta escrever *a operação b*:


In [13]:
import numpy as np

a = np.arange(20).reshape(5,4)
b = 2 * np.ones((5,4))    
c = np.arange(12,0,-1).reshape(4,3)
print('a=\n', a )
print('b=\n', b )
print('c=\n', c )

a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
b=
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
c=
 [[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]


Multiplicação de array por escalar: *b x 5*
--------------------------------------------------

In [14]:
b5 = 5 * b

print('b5=\n', b5 )

b5=
 [[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]


Soma de arrays: *a + b*
---------------------------

In [15]:
amb = a + b

print('amb=\n', amb )

amb=
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]]


Transposta de uma matriz: *a.T*
-----------------------------------

A transposta de uma matriz, troca os eixos das coordenadas. O elemento que
estava na posição *(r,c)* vai agora estar na posição *(c,r)*. O shape
da matriz resultante ficará portanto com os valores trocados. A operação
de transposição é feita através de cópia rasa, portanto é uma operação
muito eficiente e deve ser utilizada sempre que possível.

Veja o exemplo a seguir:

In [16]:
at = a.T
print('a.shape=',a.shape )
print('a.T.shape=',a.T.shape )    
print('a=\n', a )
print('at=\n', at )

a.shape= (5, 4)
a.T.shape= (4, 5)
a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
at=
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


Multiplicação de matrizes: *a x c*
------------------------------------

A multiplicação de matrizes é feita através do operador *dot*. 
Para que a multiplicação seja possível é importante que o número de
colunas do primeiro *ndarray* seja igual ao número de linhas do
segundo. As dimensões do resultado será o número de linhas do 
primeiro *ndarray* pelo número de colunas do segundo *ndarray*. Confira:

In [17]:
ac = a.dot(c)

print('a.shape:',a.shape )
print('c.shape:',c.shape )
print('a=\n',a )
print('c=\n',c )
print('ac=\n', ac )
print('ac.shape:',ac.shape )

a.shape: (5, 4)
c.shape: (4, 3)
a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
c=
 [[12 11 10]
 [ 9  8  7]
 [ 6  5  4]
 [ 3  2  1]]
ac=
 [[ 30  24  18]
 [150 128 106]
 [270 232 194]
 [390 336 282]
 [510 440 370]]
ac.shape: (5, 3)


Operações de comparação
------------------------------------

In [34]:
amenorigual10 = a <= 10
amaiorb = a > b
aigualb = a == b

print('a.shape:',a.shape,'/ b.shape:',b.shape )
print('a.dtype:',a.dtype,'/ b.dtype:',b.dtype )
print('a=\n',a )
print('b=\n',b )
print('amenorigual10=\n', amenorigual10 )
print('amenorigual10.shape:',amenorigual10.shape,'amenorigual10.dtype:',amenorigual10.dtype )
print('amaiorb=\n', amaiorb )
print('amaiorb.shape:',amaiorb.shape,'amaiorb.dtype:',amaiorb.dtype )
print('aigualb=\n', aigualb )
print('aigualb.shape:',aigualb.shape,'aigualb.dtype:',aigualb.dtype )

a.shape: (5, 4) / b.shape: (5, 4)
a.dtype: int32 / b.dtype: float64
a=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
b=
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
amenorigual10=
 [[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [False False False False]
 [False False False False]]
amenorigual10.shape: (5, 4) amenorigual10.dtype: bool
amaiorb=
 [[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
amaiorb.shape: (5, 4) amaiorb.dtype: bool
aigualb=
 [[False False  True False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
aigualb.shape: (5, 4) aigualb.dtype: bool


Note que as operações de comparação envolvendo arrays resultam em arrays booleanos. Tais arrays podem ser muito úteis para indexação, como exemplificado abaixo:

In [38]:
print('a[amenorigual10==True]=\n',a[amenorigual10==True] )
print('equivalente a')
print('a[a<=10]=\n',a[a<=10] )
print()
print('a[amaiorb==True]=\n',a[amaiorb==True] )
print('equivalente a')
print('a[a>b]=\n',a[a>b] )

a[amenorigual10==True]=
 [ 0  1  2  3  4  5  6  7  8  9 10]
equivalente a
a[a<=10]=
 [ 0  1  2  3  4  5  6  7  8  9 10]

a[amaiorb==True]=
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
equivalente a
a[a>b]=
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
